vim9script
scriptencoding utf-8
if has('osx')
	set antialias           # アンチエイリアス
endif
set columns=168           # columns width of the display
set lines=999             # lines number of lines in the display
if has('unix')            # 使用フォント(最初に見つかったフォントを使う)
	set guifont=RictyDiminished\ NF\ Regular\ 14,Ricty\ Diminished\ Regular\ 14,Noto\ Mono\ 13,Monospace\ 12
else
	set guifont=RictyDiminished\ NF\ Regular:h14,Ricty\ Diminished\ Regular:h14,MS_Gothic:h13,Monaco:h10
endif
# set linespace=-1         # 縦罫線がつながるが問題が出る可能性もあるとの事なので止めておく
# if exists('&ambiwidth')  # guifont を指定すると auto にされるらしい←勘違い?
# 	set ambiwidth=double
# endif
set guioptions-=T guioptions-=m guioptions-=r guioptions-=L guioptions+=k # ツール・バー/メニュー/スクロール・バー表示を OFF、lines, columns を維持
augroup GVIMRC
	autocmd!
	# 画面左上に表示 (help に有る通り autocmd を使わないと環境によって gvimrc の記載では無効)
	autocmd GUIEnter * winpos 0 0 | autocmd! GVIMRC | augroup! GVIMRC
	# autocmd VimEnter,GUIEnter * if &lines != 48 | set lines=48 | endif
	# ↑GTK でズレが生じるため再設定 https://github.com/vim-jp/issues/issues/1374
	# lines=999 としたのでコメントに
augroup END
# ホイール・スクロールは [Shift] 押しながらと逆にする {{{
nnoremap <ScrollWheelUp>     <S-ScrollWheelUp>
nnoremap <S-ScrollWheelUp>   <ScrollWheelUp>
nnoremap <ScrollWheelDown>   <S-ScrollWheelDown>
nnoremap <S-ScrollWheelDown> <ScrollWheelDown>
xnoremap <ScrollWheelUp>     <C-U>
xnoremap <ScrollWheelDown>   <C-D>
# }}}

def GuiOptionM(): void
	if &guioptions =~# 'M'
		silent set guioptions-=M
		if exists('g:did_install_default_menus')
			unlet g:did_install_default_menus
		endif
		if exists('g:did_install_syntax_menu')
			unlet g:did_install_syntax_menu
		endif
		execute 'source ' .. resolve(globpath(&runtimepath, 'menu.vim', 1, 1)[0])
	endif
enddef
def Toggle_menu()
	call GuiOptionM()
	if &guioptions =~# 'm'
		set guioptions-=m
	else
		set guioptions+=m
	endif
enddef
def Toggle_Toolbar()
	call GuiOptionM()
	if &guioptions =~# 'T'
		set guioptions-=T
	else
		set guioptions+=T
	endif
enddef
nnoremap <leader>cM <Cmd>call <SID>Toggle_menu()<CR>
nnoremap <leader>cT <Cmd>call <SID>Toggle_Toolbar()<CR>
