#!/bin/sh

# Example for $XDG_CONFIG_HOME/sxiv/exec/key-handler
# Called by sxiv(1) after the external prefix key (C-x by default) is pressed.
# The next key combo is passed as its first argument. Passed via stdin are the
# images to act upon, one path per line: all marked images, if in thumbnail
# mode and at least one image has been marked, otherwise the current image.
# sxiv(1) blocks until this script terminates. It then checks which images
# have been modified and reloads them.

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.

rotate() {
	file="$1"
	degree="$2"
	case "$(file -b -i "$file")" in
		image/jpeg*) jpegtran -rotate "$degree" -copy all -outfile "$file" "$file" ;;
		*)           mogrify  -rotate "$degree" "$file" ;;
	esac
}

xclipboard() {
	# if [ "$WAYLAND_DISPLAY" != "" ]; then
	# 	echo 'Please install wl-clipboard.' >&2
	# 	exit 1
	# fi
	case "$XDG_SESSION_TYPE" in
		x11)
			if command -v xsel > /dev/null ; then
				xcopy="xsel -bi"
			else
				echo "Install xsel" >&2
				exit 1
			fi
			;;
		wayland)
			if command -v xsel > /dev/null ; then
				xcopy="wl-copy"
			else
				echo "Install wl-copy" >&2
				exit 1
			fi
			;;
		*)
			echo "This script only works X11 or Wayland." >&2
			exit 1
	esac
}

case "$(uname)" in
	Darwin)
		xcopy=pbpaste
		;;
	*BSD)
		xclipboard ;;
	*)
		xclipboard ;;
esac

while read -r file ; do
	case "$1" in
		"c")        echo "$file" | $xcopy ;;
		"C-c")      echo "$file" | $xcopy ;;
		"d")        trash-put "$file" ;;
		"C-d")      trash-put "$file" ;;
		"g")        geeqie "$file" & ;;
		"C-g")      geeqie "$file" & ;;
		"e")        gimp "$file" & ;;
		"C-e")      gimp "$file" & ;;
		# "C-r")      rawtherapee "$file" & done ;;
		# "C-comma")  rotate "$file" 270 ;;
		# "C-period") rotate "$file"  90 ;;
		# "C-slash")  rotate "$file" 180 ;;
	esac
done
