vim9script
scriptencoding utf-8
set lines=999 columns=168           # columns width of the display
# if g:colors_name ==# 'solarized8' && &background ==# 'dark'
# 	# solarized8 を使っている時は、配色の違いから set termguicolors としているので、ctermbg=NONE 同様 guibg=NONE を使っている
# 	# →そのため :gui を使うと、そのまま guibg が NONE で配色がおかしくなる
# 	highlight Normal guifg=#eee8d5 guibg=#002b36
# endif
if has('unix')            # 使用フォント(最初に見つかったフォントを使う)
	set guifont=UDEV\ Gothic\ NF\ Regular\ 13,Noto\ Mono\ 13,Monospace\ 12
else
	set guifont=UDEV\ Gothic\ NF\ Regular:h13,MS_Gothic:h13,Monaco:h10
	if has('osx')
		set antialias         # アンチエイリアス
	endif
endif

# set linespace=-1         # 縦罫線がつながるが問題が出る可能性もあるとの事なので止めておく
set guioptions-=T guioptions-=m guioptions-=r guioptions-=L guioptions+=ck # ツール・バー/メニュー/スクロール・バー表示を OFF、ポップアップ・ダイアログではなくコンソールを使う lines, columns を維持
# if $GVIM_ENABLE_WAYLAND !=# '1' # ←winpos 等が効かなくなる (Ubuntu 24.10で改善され、無くても描画は乱れないので指定することはない)
augroup GVIMRC
	autocmd!
	# ↑GTK でズレが生じるため再設定 https://github.com/vim-jp/issues/issues/1374 と関係が有る?
	# 画面左上に表示 (help に有る通り autocmd を使わないと環境によって gvimrc の記載では無効+Wayland では無効)
	if !has('unix') || $XDG_SESSION_TYPE ==# 'x11' || $GDK_BACKEND ==# 'x11'
		autocmd GUIEnter * winpos 0 0
		autocmd GUIEnter * set lines=999 # lines number of lines in the display←何時からか autocmd でない箇所で 999 を指定すると Wayland の環境で横幅まで最大にされることが多くなる
	else
		autocmd GUIEnter * set lines=47 # lines number of lines in the display←何時からか autocmd でない箇所で 999 を指定すると Wayland の環境で横幅まで最大にされることが多くなる
	endif
	autocmd GUIEnter   * autocmd_delete([{group: 'GVIMRC'}])
augroup END
# endif
# ホイール・スクロールは [Shift] 押しながらと逆にする {{{
nnoremap <ScrollWheelUp>     <S-ScrollWheelUp>
nnoremap <S-ScrollWheelUp>   <ScrollWheelUp>
nnoremap <ScrollWheelDown>   <S-ScrollWheelDown>
nnoremap <S-ScrollWheelDown> <ScrollWheelDown>
xnoremap <ScrollWheelUp>     <C-U>
xnoremap <ScrollWheelDown>   <C-D>
nnoremap <C-ScrollWheelUp>   <Cmd>call gvimrc#FontSize(1)<CR>
nnoremap <C-ScrollWheelDown> <Cmd>call gvimrc#FontSize(-1)<CR>
# }}}

nnoremap <leader>cM <Cmd>call gvimrc#Menu()<CR>
nnoremap <leader>cT <Cmd>call gvimrc#Toolbar()<CR>
