vim9script
scriptencoding utf-8

var fonts: list<string>
var size: any = 13
if has('mac')
	fonts = systemlist(['system_profiler', 'SPFontsDataType'])
		->filter((_, v) => v =~ '^\s*Family:')
		->map((_, v) => substitute(v, '^[[:space:]]*Family:[[:space:]]*', '', ''))
	size = $':h{size}'
elseif has('unix')
	fonts = systemlist(['fc-list', ':style=Regular'])
		->map((_, v) => substitute(v, '^[^:]\+: \([^:]\+\):style=.\+', '\1', ''))
	size = $'\ {size}'
elseif has('win32')
	fonts = systemlist('powershell -NoProfile -Command "Get-ItemProperty ''HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts'' | Get-Member -MemberType NoteProperty | Select-Object -ExpandProperty Name"')
		->map((_, v) => substitute(v, '\s*([^)]*)$', '', ''))
		->map((_, v) => split(v, '\s*&\s*'))
		->flattennew()
	size = $':h{size}'
endif
for f in ['UDEV Gothic NF', 'Noto Mono', 'BIZ UDGothic', 'Menlo', 'Cascadia Mono', 'Monaco', 'Consolas', 'Courier', 'MS Gothic', 'Monospace']
	if count(fonts, f) != 0
		execute ($'set guifont={escape(f, ' ')}\ Regular{size}')
		break
	endif
endfor
set guioptions-=T guioptions-=m guioptions-=r guioptions-=L guioptions+=ck # ツール・バー/メニュー/スクロール・バー表示を OFF、ポップアップ・ダイアログではなくコンソールを使う lines, columns を維持
augroup GVIMRC
	autocmd!
	if !has('unix') || $XDG_SESSION_TYPE ==# 'x11' || $GDK_BACKEND ==# 'x11'
		# 画面左上に表示 (help に有る通り autocmd を使わないと環境によって gvimrc の記載では無効+Wayland では無効)
		autocmd GUIEnter * winpos 0 0
	else
		autocmd GUIEnter * gvimrc#GnomeTopLeft()
	endif
	autocmd   BufEnter * gvimrc#GnomeActive()
	autocmd   GUIEnter * autocmd_delete([{group: 'GVIMRC', event: 'GUIEnter'}])
	# autocmd GUIEnter * autocmd_delete([{group: 'GVIMRC'}])
augroup END
set lines=999 columns=168 # GTK3 環境では lines=999 を指定するウィンドウが最大化されるときがある (GTK4 では問題ない)→https://github.com/vim-jp/issues/issues/1462
# endif
# ホイール・スクロールは [Shift] 押しながらと逆にする {{{
nnoremap <ScrollWheelUp>     <S-ScrollWheelUp>
nnoremap <S-ScrollWheelUp>   <ScrollWheelUp>
nnoremap <ScrollWheelDown>   <S-ScrollWheelDown>
nnoremap <S-ScrollWheelDown> <ScrollWheelDown>
xnoremap <ScrollWheelUp>     <C-U>
xnoremap <ScrollWheelDown>   <C-D>
nnoremap <C-ScrollWheelUp>   <Cmd>call gvimrc#FontSize(1)<CR>
nnoremap <C-ScrollWheelDown> <Cmd>call gvimrc#FontSize(-1)<CR>
# }}}

nnoremap <leader>cM <Cmd>call gvimrc#Menu()<CR>
nnoremap <leader>cT <Cmd>call gvimrc#Toolbar()<CR>
if has('gui_gtk') || has('gui_win32')
	nnoremap <expr><silent> <F11> &guioptions =~# 's' ? ":set guioptions-=s<CR>" : ":set guioptions+=s<CR>"
endif
